name: tinkler
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #architecture
  stacked: ^1.6.1+1
  #navigation
  auto_route: ^0.5.0
  stacked_services: ^0.4.4+3
  #inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  stacked_hooks: ^0.1.2
  flutter_hooks: ^0.9.0
  observable_ish: ^2.1.4
  #auth and database
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  material_design_icons_flutter: ^4.0.5345
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  shared_preferences: ^0.5.8
  firebase_messaging: ^6.0.16
  flutter_facebook_login: ^3.0.0

  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  cached_network_image: ^2.3.1
  admob_flutter: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  auto_route_generator: null
  injectable_generator: null
  device_preview: ^0.4.8

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

